export const ADD_CINEMAHALL = 'ADD_CINEMAHALL';
export const SET_CINEMAHALLS = 'SET_CINEMAHALLS';
export const FETCH_CINEMAHALL = 'FETCH_CINEMAHALL';
export const FETCH_CINEMAHALLS = 'FETCH_CINEMAHALLS';
export const CHANGE_CINEMAHALL = 'CHANGE_CINEMAHALL';
export const DELETE_CINEMAHALL = 'DELETE_CINEMAHALLS';
